#!/bin/bash

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1}'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:
if [ -z "$1" ];
then
        exec conky -c "$HOME/.i3/conky_bar"
else
        exec conky -c "$HOME/.i3/conky_bar_$1"
fi
