#!/bin/sh

lock() {
	if [ -z "$WAYLAND_DISPLAY" ];
	then
		xscreensaver-command -lock
	else
		swaylock -i ~/Bilder/Background/actual &
	fi
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
